Cadastos/Cadastros.Web/Models/ErrorViewModel.cs
namespace Cadastros.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cadastos/Cadastros.Web/Models/ReturnJsonDel.cs
namespace Cadastros.Web.Models
{
    public class ReturnJsonDel
    {
        public string status { get; set; }
        public string code { get; set; }
    }
}

Cadastos/Cadastros.Web/Controllers/EmpresaController.cs
using Cadastros.Domain.DTO;
using Cadastros.Domain.Entities;
using Cadastros.Domain.IServices;
using Cadastros.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cadastros.Web.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IEmpresaService _service;
        private readonly IUFServices _ufService;
        private readonly IFornecedorService _fornecedorService;
        public EmpresaController(IEmpresaService service, IUFServices uFServices, IFornecedorService fornecedorService)
        {
            _service = service;
            _ufService = uFServices;
            _fornecedorService = fornecedorService;
        }
        public IActionResult Index()
        {
            return View(_service.FindAll());
        }
        public JsonResult ListJson()
        {
            return Json(_service.FindAll());
        }
        public IActionResult Create()
        {
            ViewData["ufId"] = new SelectList(_ufService.FindAll(), "id", "nome", "Select...");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, nomeFantasia, cNPJ, ufId")] EmpresaDTO empresa)
        {
            if (ModelState.IsValid)
            {
                if (await _service.Save(empresa) > 0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["ufId"] = new SelectList(_ufService.FindAll(), "id", "nome", "Select...");
            return View(empresa);
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var empresa = await _service.FindById(id);
            ViewData["ufId"] = new SelectList(_ufService.FindAll(), "id", "nome", "Select...");
            return View(empresa);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, [Bind("id, nomeFantasia, cNPJ, ufId")] EmpresaDTO empresa)
        {
            if (!(id == empresa.id))
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (await _service.Save(empresa) > 0)
                    return RedirectToAction(nameof(Detalhes), new { id = empresa.id} );
            }
            ViewData["ufId"] = new SelectList(_ufService.FindAll(), "id", "nome", "Select...");
            return View(empresa);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "Success",
                code = "200"
            };
            if (await _service.Delete(id ?? 0) <= 0)
            {
                retDel = new ReturnJsonDel
                {
                    status = "Error",
                    code = "400"
                };
            }
            return View();
        }
        public async Task<IActionResult> Detalhes(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var empresa = await _service.FindById(id);
            empresa.listaFornecedor = _fornecedorService.FindByEmpresaId(id);
            return View(empresa);
        }
    }
}

Cadastos/Cadastros.Web/Controllers/FornecedorController.cs
using Cadastros.Application.Service.SQLServerServices;
using Cadastros.Domain.DTO;
using Cadastros.Domain.Entities;
using Cadastros.Domain.IServices;
using Cadastros.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cadastros.Web.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorService _fornecedorService;
        private readonly IEmpresaService _empresaService;
        private readonly ITelefoneService _telefoneService;
        public FornecedorController(IFornecedorService service, IEmpresaService empresaService, ITelefoneService telefoneService)
        {
            _fornecedorService = service;
            _empresaService = empresaService;
            _telefoneService = telefoneService;
        }
        public async Task<IActionResult> Index()
        {
            var list = _fornecedorService.FindAll();
            return View(list);
        }
        public JsonResult ListJson()
        {
            return Json(_fornecedorService.FindAll());
        }
        public IActionResult Create()
        {
            ViewData["empresaId"] = new SelectList(_empresaService.FindAll(), "id", "nomeFantasia", "Select...");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("id, empresaId, nome, cpf_cnpj, rg, pessoaFisica")] FornecedorDTO fornecedor)
        {
            if (ModelState.IsValid)
            {
                if (await _fornecedorService.Save(fornecedor) > 0)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["empresaId"] = new SelectList(_empresaService.FindAll(), "id", "nome", "Select...");
            return View(fornecedor);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJsonDel
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _fornecedorService.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJsonDel
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJsonDel
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
        public async Task<IActionResult> Detalhes(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var empresa = await _fornecedorService.FindById(id);
           
            empresa.telefoneList = _telefoneService.FindAll().Where(p => p.fornecedorId == id);
            return View(empresa);
        }
    }
}

Cadastos/Cadastros.Web/Controllers/HomeController.cs
using Cadastros.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cadastros.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadastos/Cadastros.Web/Views/Empresa/Create.cshtml
@model Cadastros.Domain.DTO.EmpresaDTO
<h1>Criar</h1>
<h4>Empresa</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeFantasia" class="control-label">Nome fantasia</label>
                <input asp-for="nomeFantasia" class="form-control" />
                <span asp-validation-for="nomeFantasia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cNPJ" class="control-label">CNPJ</label>
                <input asp-for="cNPJ" class="form-control" />
                <span asp-validation-for="cNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ufId" class="control-label"></label>
                <select asp-for="ufId" class="form-control" asp-items="ViewBag.ufId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Cadastos/Cadastros.Web/Views/Empresa/Detalhes.cshtml
@model Cadastros.Domain.DTO.EmpresaDTO

<h1>Detalhes</h1>
<h4>Empresa</h4>

<div class="row">
    <table>
        <td width="40%">
            <ul class="list-group" >
                <label asp-for="nomeFantasia">Nome Fantasia</label>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <b>@Model.nomeFantasia</b>
                </li>
                <label asp-for="ufId">Unidade Federal</label>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <b>@Model.ufDTO.nome'</b>
                </li>
                <label asp-for="cNPJ">Unidade Federal</label>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <b>@Model.cNPJ</b>
                </li>
            </ul>
        </td>
        <td width="60%">
            <ul>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.id">Editar</a>
            </ul>
            <ul>
                <a class="btn btn-danger" onclick="deleteEmpresa(@Model.id)">Deletar</a>
            </ul>
        </td>
    </table>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a> Id </a>
                </th>
                <th>
                    <a> Nome </a>
                </th>
                <th>
                    <a> CPF_CNPJ </a>
                </th>
                <th>
                    <a class="btn btn-primary" asp-controller="Fornecedor" asp-action="Create">Adicionar</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.listaFornecedor)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id )
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cpf_cnpj)
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Fornecedor" asp-action="Detalhes" asp-route-id="@item.id" >Detalhes</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script>
            const deleteEmpresa = (idParam) => {
                msgModalMessage(`Deseja realmente excluir o registro ${idParam}?`, () => {
                    $.ajax({
                        url: `@Url.Action("Delete")`,
                        method: 'POST',
                        data: {
                            id: idParam
                        },
                        success: (resp) => {
                            if (resp.code == '200') {
                                liveToastMessage(`O Registro ${idParam} foi excluído.`, 'Empresa');
                                setTimeout(() => { window.location.reload(); }, 4000);
                            }
                        }
                    });
                    closeMsgModalMessage();
                    setTimeout(() => { window.location.href = '@Url.Action("Index")'; }, 1000);
                });
            }
        </script>
    }
}

Cadastos/Cadastros.Web/Views/Empresa/Edit.cshtml
@model Cadastros.Domain.DTO.EmpresaDTO

<h1>Editar</h1>
<h4>Empresa</h4>
<table>
    <td width="40%" >
        <div class="row">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="id" />
                <div class="form-group">
                    <label asp-for="nomeFantasia">Nome Fantasia</label>
                    <input asp-for="nomeFantasia" type="text" class="form-control">
                </div>
                <div class="form-row ">
                    <div class="form-group">
                            <label asp-for="cNPJ">CNPJ</label>
                            <input asp-for="cNPJ" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                            <label asp-for="ufId" class="control-label"></label>
                            <select asp-for="ufId" class="form-control" asp-items="ViewBag.ufId"></select>
                    </div>
                </div>
                <div class="form-group my-4">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </td>

</table>

<div>
    <a class="btn btn-primary" asp-action="Detalhes" asp-route-id="@Model.id">Detalhes</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script>
        const deleteEmpresa = (idParam) => {
            msgModalMessage(`Deseja realmente excluir o registro ${idParam}?`, () => {
                $.ajax({
                    url: `@Url.Action("Delete")`,
                    method: 'POST',
                    data: {
                        id: idParam
                    },
                    success: (resp) => {
                        if (resp.code == '200') {
                            liveToastMessage(`O Registro ${idParam} foi excluído.`, 'Empresa');
                            setTimeout(() => { window.location.reload(); }, 4000);
                        }
                    }
                });
                closeMsgModalMessage();
                setTimeout(() => { window.location.href = '@Url.Action("Index")'; }, 2000);
            });
        }
    </script>
    }
}

Cadastos/Cadastros.Web/Views/Empresa/Index.cshtml
@model IEnumerable<Cadastros.Domain.DTO.EmpresaDTO>
<div class="text-center">
    <h1 class="display-4">Menu de empresas</h1>
</div>
<p>
    <a class="btn btn-primary" asp-action="Create">Criar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a> Id </a>
            </th>
            <th>
                <a> Nome Fantasia </a>
            </th>
            <th>
                <a> CNPJ </a>
            </th>
            <th>
                <a> UF </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id )
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nomeFantasia) 
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cNPJ)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ufId)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Detalhes" asp-route-id="@item.id">Detalhes</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script>
        const deleteEmpresa = (idParam) => {
            msgModalMessage(`Deseja realmente excluir o registro ${idParam}?`, () => {
                $.ajax({
                    url: `@Url.Action("Delete")`,
                    method: 'POST',
                    data: {
                        id: idParam
                    },
                    success: (resp) => {
                        if (resp.code == '200') {
                            liveToastMessage(`O Registro ${idParam} foi excluído.`, 'Empresa');
                            setTimeout(() => { window.location.reload(); }, 4000);
                        }
                    }
                });
                closeMsgModalMessage();
            });
        }
    </script>
}

Cadastos/Cadastros.Web/Views/Fornecedor/Create.cshtml
@model Cadastros.Domain.DTO.FornecedorDTO
<h1>Adicionar</h1>
<h4>Fornecedor</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="empresaId" class="control-label"></label>
                <select asp-for="empresaId" class="form-control" asp-items="ViewBag.empresaId"></select>
            </div>

            <div class="form-group">
                <label asp-for="nome" class="control-label">Nome</label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-check form-switch">
                <input asp-for="pessoaFisica" class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                <label asp-for="pessoaFisica" class="form-check-label" for="flexSwitchCheckDefault">Pessoa Fisica?</label>
            </div>
            <div class="form-group">
                <label asp-for="cpf_cnpj" class="control-label">CNPJ ou CPF</label>
                <input asp-for="cpf_cnpj" class="form-control" />
                <span asp-validation-for="cpf_cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rg" class="control-label">RG</label>
                <input asp-for="rg" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="dataDeNascimento"  class="control-label" for="date">Data de Nascimento</label>
                <div class="col-sm-4">
                    <div class="input-group">
                        <div class="input-group-addon round-form">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input asp-for="dataDeNascimento" type="text" class="form-control round-form" id="dtnasc" name="dtnasc" placeholder="DD/MM/YYYY" required autocomplete="false" value="">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Cadastos/Cadastros.Web/Views/Fornecedor/Detalhes.cshtml
@model Cadastros.Domain.DTO.FornecedorDTO

<h1>Detalhes</h1>
<h4>Fornecedor</h4>

<div class="row">

    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Nome
            <b>@Model.nome</b>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            CPF ou CNPJ
            <b>@Model.cpf_cnpj</b>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            RG
            <b>@Model.rg</b>
        </li>

    </ul>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a> Id </a>
                </th>
                <th>
                    <a> Numero </a>
                </th>
                <th>
                    <a class="button"> Adicionar </a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.telefoneList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id )
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.numero)
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                        <a class="btn btn-danger" href="#" onclick="deleteEmpresa(@item.id)">Deletar</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Cadastos/Cadastros.Web/Views/Fornecedor/Index.cshtml
@model IEnumerable<Cadastros.Domain.DTO.FornecedorDTO>

<div class="text-center">
    <h1 class="display-4">Menu de fornecedores</h1>
</div>
<p>
    <a class="btn btn-primary" asp-action="Create">Adicionar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a> Id </a>
            </th>
            <th>
                <a> Nome </a>
            </th>
            <th>
                <a> Empresa </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id )
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empresaId)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Detalhes" asp-route-id="@item.id">Detalhes</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        const deleteFornecedor = (idParam) => {
            msgModalMessage(`Deseja realmente excluir o registro ${idParam}?`, () => {
                $.ajax({
                    url: `@Url.Action("Delete")`,
                    method: 'POST',
                    data: {
                        id: idParam
                    },
                    success: (resp) => {
                        var msg = `O Registro ${idParam} foi excluído.`;
                        if (!(resp.code == '200')) {
                            msg = resp.status;
                        }
                        liveToastMessage(msg, 'Fornecedor');
                        setTimeout(() => { window.location.reload(); }, 4000);
                    }
                });
                closeMsgModalMessage();
            });
        }
    </script>
}

Cadastos/Cadastros.Web/Views/Home/Index.cshtml
<div class="text-center " >
    <h1 class="display-4">Fase de testes</h1>
</div>

Cadastos/Cadastros.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site de cadastros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cadastros.Web.styles.css" asp-append-version="true" />
</head>
<body class="bg-secondary">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastros.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Empresa" asp-action="Index">Empresa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cadastros.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Messages using Toasts Component -->
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <img src="~/img/logo.png" class="rounded me-2" width="24" height="24" alt="...">
                <strong class="me-auto">CMSSite - <span id="toast-origin"></span></strong>
                <small id="toast-time">11:00</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body" id="toast-body">
                Hello, world! This is a toast message.
            </div>
        </div>
    </div>

    <!-- Messages using Modal Component -->
    <div class="modal fade" id="msgModal" tabindex="-1" aria-labelledby="msgModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="msgModalLabel">CMSSite - Message</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="modal-body" class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button id="btnModalCallback" type="button" class="btn btn-primary">Ok</button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>